/**
 * Bambushain
 *
 * Bambushain Server API
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: panda.helferlein@bambushain.app
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.bambushain.api.models

import app.bambushain.api.models.FreeCompany

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param race 
 * @param name 
 * @param world 
 * @param id 
 * @param customFields 
 * @param freeCompany 
 */
@Serializable
data class Character (

    @SerialName(value = "race")
    val race: Character.Race,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "world")
    val world: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "customFields")
    val customFields: kotlin.collections.List<@Contextual kotlin.Any>? = null,

    @SerialName(value = "freeCompany")
    val freeCompany: FreeCompany? = null

) {

    /**
     * 
     *
     * Values: hyur,elezen,lalafell,miqote,roegadyn,auRa,hrothgar,viera
     */
    @Serializable
    enum class Race(val value: kotlin.String) {
        @SerialName(value = "Hyur") hyur("Hyur"),
        @SerialName(value = "Elezen") elezen("Elezen"),
        @SerialName(value = "Lalafell") lalafell("Lalafell"),
        @SerialName(value = "Miqote") miqote("Miqote"),
        @SerialName(value = "Roegadyn") roegadyn("Roegadyn"),
        @SerialName(value = "AuRa") auRa("AuRa"),
        @SerialName(value = "Hrothgar") hrothgar("Hrothgar"),
        @SerialName(value = "Viera") viera("Viera");
    }
}

