/**
 * Bambushain
 *
 * Bambushain Server API
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: panda.helferlein@bambushain.app
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.bambushain.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param job 
 * @param characterId 
 * @param id 
 * @param level 
 */
@Serializable
data class Crafter (

    @SerialName(value = "job")
    val job: Crafter.Job,

    @SerialName(value = "characterId")
    val characterId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "level")
    val level: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: carpenter,blacksmith,armorer,goldsmith,leatherworker,weaver,alchemist,culinarian,miner,botanist,fisher
     */
    @Serializable
    enum class Job(val value: kotlin.String) {
        @SerialName(value = "Carpenter") carpenter("Carpenter"),
        @SerialName(value = "Blacksmith") blacksmith("Blacksmith"),
        @SerialName(value = "Armorer") armorer("Armorer"),
        @SerialName(value = "Goldsmith") goldsmith("Goldsmith"),
        @SerialName(value = "Leatherworker") leatherworker("Leatherworker"),
        @SerialName(value = "Weaver") weaver("Weaver"),
        @SerialName(value = "Alchemist") alchemist("Alchemist"),
        @SerialName(value = "Culinarian") culinarian("Culinarian"),
        @SerialName(value = "Miner") miner("Miner"),
        @SerialName(value = "Botanist") botanist("Botanist"),
        @SerialName(value = "Fisher") fisher("Fisher");
    }
}

