/**
 * Bambushain
 *
 * Bambushain Server API
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: panda.helferlein@bambushain.app
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.bambushain.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param startDate 
 * @param endDate 
 * @param color 
 */
@Serializable
data class Event (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @Contextual @SerialName(value = "startDate")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "endDate")
    val endDate: java.time.LocalDate,

    @SerialName(value = "color")
    val color: kotlin.String

)

