/**
 * Bambushain
 *
 * Bambushain Server API
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: panda.helferlein@bambushain.app
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.bambushain.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param job 
 * @param characterId 
 * @param id 
 * @param level 
 * @param gearScore 
 */
@Serializable
data class Fighter (

    @SerialName(value = "job")
    val job: Fighter.Job,

    @SerialName(value = "characterId")
    val characterId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "level")
    val level: kotlin.String? = null,

    @SerialName(value = "gearScore")
    val gearScore: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: paladin,warrior,darkKnight,gunbreaker,whiteMage,scholar,astrologian,sage,monk,dragoon,ninja,samurai,reaper,bard,machinist,dancer,blackMage,summoner,redMage,blueMage,viper,pictomancer
     */
    @Serializable
    enum class Job(val value: kotlin.String) {
        @SerialName(value = "Paladin") paladin("Paladin"),
        @SerialName(value = "Warrior") warrior("Warrior"),
        @SerialName(value = "DarkKnight") darkKnight("DarkKnight"),
        @SerialName(value = "Gunbreaker") gunbreaker("Gunbreaker"),
        @SerialName(value = "WhiteMage") whiteMage("WhiteMage"),
        @SerialName(value = "Scholar") scholar("Scholar"),
        @SerialName(value = "Astrologian") astrologian("Astrologian"),
        @SerialName(value = "Sage") sage("Sage"),
        @SerialName(value = "Monk") monk("Monk"),
        @SerialName(value = "Dragoon") dragoon("Dragoon"),
        @SerialName(value = "Ninja") ninja("Ninja"),
        @SerialName(value = "Samurai") samurai("Samurai"),
        @SerialName(value = "Reaper") reaper("Reaper"),
        @SerialName(value = "Bard") bard("Bard"),
        @SerialName(value = "Machinist") machinist("Machinist"),
        @SerialName(value = "Dancer") dancer("Dancer"),
        @SerialName(value = "BlackMage") blackMage("BlackMage"),
        @SerialName(value = "Summoner") summoner("Summoner"),
        @SerialName(value = "RedMage") redMage("RedMage"),
        @SerialName(value = "BlueMage") blueMage("BlueMage"),
        @SerialName(value = "Viper") viper("Viper"),
        @SerialName(value = "Pictomancer") pictomancer("Pictomancer");
    }
}

