.build-base:
  image:
    name: registry.ulbricht.casa/docker-images/android-native-app:latest
    pull_policy: always
  before_script:
    - chmod +x ./gradlew
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .gradle

stages:
  - lint
  - build
  - deploy

lint-debug-app:
  stage: lint
  extends:
    - .build-base
  script:
    - ./gradlew -Pci --console=plain lintDebug -PbuildDir=lint
  artifacts:
    paths:
      - app/lint/reports/lint-results-debug.html
    expose_as: "lint-report"
    when: always

lint-release-app:
  stage: lint
  extends:
    - .build-base
  script:
    - ./gradlew -Pci --console=plain lintRelease -PbuildDir=lint
  artifacts:
    paths:
      - app/lint/reports/lint-results-release.html
    expose_as: "lint-report"
    when: always
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main"

build-release-app:
  stage: build
  extends:
    - .build-base
  script:
    - mkdir -p /opt/secure
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ./gradlew -Pci --console=plain bundle -PbuildDir=build
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main"

deploy-internal-test-app:
  stage: deploy
  extends:
    - .build-base
  before_script:
    - bundle update
  script:
    - mkdir -p /opt/secure
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - bundle exec fastlane android internal
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
      when: never

deploy-tagged-test-app:
  stage: deploy
  extends:
    - .build-base
  before_script:
    - bundle update
  script:
    - bundle exec fastlane android internal
  rules:
    - if: $CI_COMMIT_TAG
      when: never
