update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :internal do
    gradle(task: "clean assemble")
    upload_to_play_store(track: "internal", build_type: "Debug")
  end
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
